### ISSUE TITLE
data9

### ISSUE THREAD

**Issue by Afei-L** [SpyrosMouselinos/TF2GAIN#1]
I run the code, but spyder shows data9.csv can't be found. Could you share the data though the email? I greatly appreciate. Thanks a lot.
email: lpflpf@126.com

**Comment by SpyrosMouselinos** [comment]
The data9.csv is a dataset belonging to a company I used to work, thus proprietary. You can use the other options available that were also used in the original paper

**Comment by Afei-L** [comment]
Thanks a lot for your prompt reply.


Best regards,
Pengfei Lin





------------------ Original ------------------
From: Spyros Mouselinos ***@***.***&gt;
Date: Tue, Jul 13, 2021 11:19 PM
To: SpyrosMouselinos/TF2GAIN ***@***.***&gt;
Cc: Afei-L ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [SpyrosMouselinos/TF2GAIN] data9 (#1)





 
The data9.csv is a dataset belonging to a company I used to work, thus proprietary. You can use the other options available that were also used in the original paper
